# Generated by Django 2.2.2 on 2019-06-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellido1', models.CharField(max_length=35)),
                ('Apellido2', models.CharField(max_length=35)),
                ('Nombre', models.CharField(max_length=35)),
                ('DNI', models.CharField(max_length=35)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
    ]
